version: '3.7'
services:
  refinery:
    container_name: refinery
    build:
      context: ./
      dockerfile: Dockerfile
      target: build
    command: npm run dev:docker --prefix ./
    ports:
      - ${REFINERY_PORT:-8081}:${REFINERY_PORT:-8081}
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
volumes:
  pgdata:
